### ISSUE TITLE
Blurry UI

### ISSUE THREAD

**Issue by Bluskript** [antfu/vscode-browse-lite#1]
System: Linux amd64
Issue: UI is blurry when viewing pages
![image](https://user-images.githubusercontent.com/52386117/109506369-8ec07900-7a6b-11eb-927b-1690e97933c6.png)

**Comment by philippdormann** [comment]
+1 , also experiencing this issue when visiting any URL (also applies for local vite projects if that is relevant)

**Comment by antfu** [comment]
This is currently a limitation with our approach (headless Chromium with screencasting, see [Browser Preview](https://github.com/auchenberg/vscode-browser-preview) for more). I will try to explore this and see if we can have a better solution for this, or maybe an option to prioritize over "speed"/"quality". Thanks for bringing this up!

**Comment by antfu** [comment]
From v0.1.3, now you can configure the quality via:

```jsonc
  "browse-lite.format": "png",
  "browse-lite.quality": 100,
```

Let me know if that makes any improvements for you, thanks!

**Comment by philippdormann** [comment]
Hi!
Unfortunately, that does not help.

However, I found a solution yesterday 🎉
My default Chrome installation (`Version 88.X`) has the blurry UI issue.

Testing with a custom chromium instance like `Version 91.X`, the UI is crystal clear 🔮

I'm still trying to figure out, whether it's an actual issue with the version or Windows file paths🤔

Will get back to you later with exact versions and hopefully more details ✌

**Comment by philippdormann** [comment]
Hey 👋

did some quick testing

## working/ crystal clear UI
- Google Chrome Version 91.0.4434.0 canary
- Google Chrome Version 90.0.4427.5 dev
- Microsoft Edge Version 90.0.810.0 canary
- Microsoft Edge Version 90.0.803.0 dev

## 🐞 blurry pages:
- Google Chrome Version 88.0.4324.190 stable
- Microsoft Edge Version 88.0.705.81 stable

so I guess we can point that issue to Chromium 88 (<90) 🤷‍♂️

**Comment by warpdesign** [comment]
Same problem on Mac/bigSur. Funny thing is that depending on the vscode-browser-lite width, rendering becomes crystal clear. A very small width fixes the problem.

I think this is related to this issue https://github.com/auchenberg/vscode-browser-preview/issues/92

Unfortunately I haven't had time to look into it further.

**Comment by antfu** [comment]
Hey guys, I kinda believe I found the problem. Please upgrade to 0.2.0 to see if it still persists. Thanks

**Comment by philippdormann** [comment]
![image](https://user-images.githubusercontent.com/17651032/109948017-37741000-7cda-11eb-8e91-c8799e426688.png)

Hey @antfu 👋
Upgraded to 0.2.1, it's still blurry for me, unfortunately
(judging by the quality, it looks like a compressed jpeg - even with 100% quality setting)

so yeah, I believe it got slightly better but I wouldn't call it a native browing experience ^^

**Comment by antfu** [comment]
@philippdormann Can I have the resolutions of your screen?

**Comment by philippdormann** [comment]
sure!
my display is 1920x1080 with Windows scaling set at 100%

the image looks the same on all tested browsers and when switching between jpeg/png btw

**Comment by auchenberg** [comment]
@philippdormann Given screencasting is working as a stream of PNGs, I don't think we'll ever get to match the equality of a native renderer.

**Comment by brandonhaire** [comment]
It looks like the content window has better resolution (still not browser quality) but the embedded debug page still has really low resolution
