### ISSUE TITLE
FR: add `--allow-file-access-from-files` to default runtime arguments ... in trusted workspaces

### ISSUE THREAD

**Issue by GitMensch** [antfu/vscode-browse-lite#10]
Reasoning: This is an extension for developers which will open local files - of course these should be able to include local files...
See https://stackoverflow.com/questions/4558160/xsl-not-working-in-google-chrome for some details (and the reason that this is not the default in chrome, as it also isn't in firefox, which _is_ reasonable for a browser - but not necessarily for a preview of developer-local files).

As vscode introduced the trusted workspace concept it seems very reasonable to always add this option in trusted workspaces, while leaving it out otherwise. This is also the core difference to #9 (which would be "only if the user specified, and then always").

**Comment by iPixelOldC** [comment]
我修复了这个问题，并且已经推了个pr。:D  #17 

Baidu Translate:
I fixed this problem and have pushed a pr. :D #17
