### ISSUE TITLE
extension now suggests debugger for chrome/edge 🤔

### ISSUE THREAD

**Issue by kinghat** [antfu/vscode-browse-lite#16]
latest release added this pr: https://github.com/antfu/vscode-browse-lite/pull/7 but the debugger for chrome is depreciated as its built into vscode now: https://github.com/Microsoft/vscode-chrome-debug#rotating_light-important and you get this popup when browse-lite is loaded:
![image](https://user-images.githubusercontent.com/16073360/132056745-55116feb-c389-4071-92da-21fb0d48dc8f.png)

**Comment by tim-hilt** [comment]
@kinghat how was the issue completed? Can you debug via browse-lite?

**Comment by kinghat** [comment]
> @kinghat how was the issue completed? Can you debug via browse-lite?

im sorry, i dont remember. it must have worked itself out.
