### ISSUE TITLE
"Failed to launch the browser process"

### ISSUE THREAD

**Issue by chiubaca** [antfu/vscode-browse-lite#3]
Oh i've waited for an extension that can do this! I was excited to try it but I'm getting this error in vs code:

```
Failed to launch the browser process! spawn C:\Program Files (x86)\Google\Chrome\Application\chrome.exe ENOENT TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
```
![image](https://user-images.githubusercontent.com/18376481/109837676-540e3a80-7c3d-11eb-9695-5ee25c998556.png)

I don't have Google Chrome installed, is that why? I do have Edge though, could the extension use that instead if Chromium is a dependency?

**Comment by antfu** [comment]
Should be fixed. But since I don't have a Windows PC to test out, you can help with that? Thanks!

**Comment by chiubaca** [comment]
I've upgraded to v0.2.1. Getting a slightly different error now:

`Cannot read property 'prototype' of undefined`

![image](https://user-images.githubusercontent.com/18376481/109994774-8be0b500-7d05-11eb-820c-87db791b835e.png)

**Comment by yountha-progrmmers** [comment]
> I've upgraded to v0.2.1. Getting a slightly different error now:
> 
> `Cannot read property 'prototype' of undefined`
> 
> ![image](https://user-images.githubusercontent.com/18376481/109994774-8be0b500-7d05-11eb-820c-87db791b835e.png)

i use Live Preview and it work well
![Screenshot_20240929_154047](https://github.com/user-attachments/assets/52834a60-d62a-479b-86c3-df793deaca7e)
