### ISSUE TITLE
Add console output

### ISSUE THREAD

**Issue by rhewy** [antfu/vscode-browse-lite#34]
### New Feature
Is it possible to expose or redirect console output such as console.log() to a new or existing window within VSCode?

### Suggested solution

Add a Browse Lite console drawer to the bottom of VSCode
![image](https://user-images.githubusercontent.com/4993063/202080163-24f92cfb-87a8-4908-a3c2-03119c4e274e.png)

### Alternative

Add a right click inspect

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
We do support open DevTools (the bug icon).
