### ISSUE TITLE
在vscode中无法打开控制台出现（调试连接已关闭。原因: WebSocket 已断开连接，准备就绪时，打开Dev Tools即可重新连接。 ）的错误提示

### ISSUE THREAD

**Issue by TsingYi1263** [antfu/vscode-browse-lite#39]
![image](https://user-images.githubusercontent.com/92976971/225277773-2b457fbb-7153-4196-a209-d4d2b1ebffcb.png)
经过排查无法发现问题所在，请求帮助

**Comment by foureyeschao** [comment]
问题依然存在，v0.3.2还是存在以上问题。

**Comment by youlan2333** [comment]
me too

**Comment by antfu** [comment]
Duplicated #41
