### ISSUE TITLE
Blurry rendering

### ISSUE THREAD

**Issue by Snir-Dekel** [antfu/vscode-browse-lite#4]
Version: 0.2.6

low resolution rendering on browser lite when window.zoomLevel (in setting.json) is not set to 0 (default). FHD resolution 91.79 PPI

demonstration on lite browser extension (window.zoomLevel is set to 1):
![Screenshot_5](https://user-images.githubusercontent.com/66528853/111869683-276e5880-8989-11eb-94b9-733975aa40f3.png)
on my normal browser:
![Screenshot_5](https://user-images.githubusercontent.com/66528853/111870174-c98f4000-898b-11eb-8167-2565274964e6.png)

**Comment by antfu** [comment]
See #1
