### ISSUE TITLE
devTools doesn't  work with chrome 111

### ISSUE THREAD

**Issue by j-avila** [antfu/vscode-browse-lite#41]
### Describe the bug

I'm trying to inspect some code on the dev tools but the next message appears over and over on vsCode
![image](https://user-images.githubusercontent.com/1820321/226111809-b3d8fca5-3518-4dcc-9292-4028e82d4534.png)
PD:  I love this extension <3 

### Reproduction

just open the dev tools

### System Info

```Shell
This happens on mac OSX ventura 12.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Wombosvideo** [comment]
The title suggests that DevTools worked fine before Chrome version 111. Can you confirm this?

**Comment by j-avila** [comment]
Actually yes. Before the chrome update browse lite was my browser for work by default, But after this can't use it anymore

**Comment by debasispanigrahi** [comment]
Does not work for latest chrome version

**Comment by chitoadinugraha** [comment]
Doesn't work on chrome 113 on Windows 11 too

**Comment by CalebUsadi** [comment]
See the above mention for a solution to this issue.

**Comment by jeffreyschultz** [comment]
I am seeing this issue with Chrome 114. Is the only path forward at this time to downgrade Chrome to 110?

**Comment by laurentpayot** [comment]
I’m also having this bug with Chrome version 115.0.5790.56 on Ubuntu 23.04.
Changes between version 110 and 111 are listed [here](https://chromium.googlesource.com/chromium/src/+log/110.0.5481.186..111.0.5563.53) but the list is many pages long :roll_eyes:

**Comment by laurentpayot** [comment]
I also have tried to disable `chrome://flags/#devtools-tab-target`, no changes.
Any idea?

**Comment by crunchwrap89** [comment]
I cannot get the dev tools and debug for this extensions to work with chrome version 115. 
Looks like this issue has persisted for a while. 

@antfu is this extension still active? 
Unfortunately i cannot downgrade the chrome version as its controlled by my current organization

**Comment by CalebUsadi** [comment]
I'm working on building Chromium myself to identify specifically what the breaking changes are, which is taking a while. The only change in the relevant update that involves DevTools seems to be [this one](https://chromium.googlesource.com/chromium/src/+/4c27f2d50bea7cbae6bbf710a74b2fcc97a3d392).

@crunchwrap89, I was not able to "downgrade," I instead installed the specified version of Chromium alongside my Chrome install, and pointing browse-lite to it in the settings. Is that possible for you?

**Comment by crunchwrap89** [comment]
@CalebUsadi okay yeah that might actually be possible, I will give it a try :). Thanks

**Comment by ipcjs** [comment]
#40 has fixed the bug by add the `--remote-allow-origins=*` argument, but `v0.3.2` does not include the argument. 
@antfu, can you please release a new version?

![image](https://github.com/antfu/vscode-browse-lite/assets/4396864/0321c2d6-c3fa-49f3-b7b4-f37dbb06b888)

**Comment by ipcjs** [comment]
currently, adding `"browse-lite.otherArgs": "--remote-allow-origins=*"` to setting.json can temporarily fix the bug.

**Comment by laurentpayot** [comment]
@ipcjs Your settings.json fix is working great for me. Thanks a lot! :+1:

**Comment by antfu** [comment]
@ipcjs Oh sorry I forgot to do the release, thanks for the reminder. Just released.

**Comment by laurentpayot** [comment]
@antfu with the new release the browser panel is empty, and the devtools too (bottom panel on the screenshot) :confused: 

![image](https://github.com/antfu/vscode-browse-lite/assets/2776142/d838c6e8-305b-4986-b3b4-c5d3196a0579)

**Comment by laurentpayot** [comment]
It fixed it. Thanks!
