### ISSUE TITLE
是否可以加一个复制粘贴功能，目前粘贴回直接出现在url中

### ISSUE THREAD

**Issue by Daixs020** [antfu/vscode-browse-lite#46]
### Clear and concise description of the problem

目前打开网页后 在文本框粘贴会直接显示在url中 网页内部只能用手打文字

### Suggested solution

目前打开网页后 在文本框粘贴会直接显示在url中 网页内部只能用手打文字

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by codespearhead** [comment]
@Daixs020 The clipboard does seem to be acting up inside Browser Lite.

Are you willing to help further investigate this and submit a pull request?
