### ISSUE TITLE
Clipboard issues when copy / pasting

### ISSUE THREAD

**Issue by schickling** [antfu/vscode-browse-lite#5]
Given that this extension is based on "screencasting", there is probably some extra handling needed for dealing with "advanced keyboard input" like keyboard shortcuts e.g. for copy / pasting. This currently manifests in a few issues/limitations:

- You can't select text and hit e.g. CMD + C to copy the text to your clipboard (this neither works in the browser preview view nor in the debugger view)
- You can't select text and right click to open the context menu to "manually copy" (this seems to work ok-ish in the debugger view but doesn't work in the browser preview view)

**Comment by 111andre111** [comment]
+1 I really like the extension and for using it I would find the copy and paste functionality quite important.

**Comment by AnzerWall** [comment]
+1

**Comment by IgnusG** [comment]
Pasting to the website just pastes the text into the URL bar at the top for me. Would be great for that to work although not sure

**Comment by Lorioux** [comment]
1+ same
