### ISSUE TITLE
Add chrome bookmark panel

### ISSUE THREAD

**Issue by jackiotyu** [antfu/vscode-browse-lite#55]
### Clear and concise description of the problem

I have created a VSCode extension that parses and displays all bookmarks from the Chrome browser. I believe that if `Browse Lite` could add a bookmark panel to the activity bar, it would be very convenient for browsing documents and similar operations through `Browse Lite`.😀
<img width="603" alt="image" src="https://github.com/antfu/vscode-browse-lite/assets/31788042/3029e4df-f82a-4def-919a-7b721c398dcb">

https://marketplace.visualstudio.com/items?itemName=jackiotyu.browser-bookmark
https://github.com/jackiotyu/vscode-browser-bookmark/blob/main/src/lib/chromePlugin.ts

### Suggested solution

Add an bookmark panel in activity bar.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I think it would be out-of-scope of this extension. I think we have exposed enough API to allow another extension to interact with/control the panels. Feel free to raise in another issue if the API could be improved.

**Comment by jackiotyu** [comment]
Okay, thanks for you answer.
