### ISSUE TITLE
can't launch browse lite by F1 ('browse-lite.open' failed)

### ISSUE THREAD

**Issue by CreatorB** [antfu/vscode-browse-lite#6]
Hi, Yesterday this plugin working well on mine, but today I can't launch browse lite on my visual studio code, getting error `Command 'Browse Lite: Open...' resulted in an error (Running the contributed command: 'browse-lite.open' failed.)`. 

Any help?, please.

![image](https://user-images.githubusercontent.com/6529730/120997691-9e113a00-c7b1-11eb-8eb7-a64fd6277a45.png)

**Comment by agenordebriat** [comment]
Same thing here (on latest macOS and VS Code versions), I cannot preview any file with 0.2.9.
I had to go back to 0.2.8 to get everything working back again. 
I'll happily provide you any information you might need to fix that.

**Comment by CreatorB** [comment]
> Same thing here (on latest macOS and VS Code versions), I cannot preview any file with 0.2.9.
> I had to go back to 0.2.8 to get everything working back again.
> I'll happily provide you any information you might need to fix that.

Really helped, it's work. Thanks, A lot mate.
